apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  finalizers:
  - k8s.v1.cni.cncf.io/kubeMacPool
  generation: 5
  labels:
    kubevirt.io/vm: sriov-vm1
  name: sriov-vm1
  namespace: sriov-test-sriov
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: sriov-vm1
        kubevirt.io/vm: sriov-vm1
    spec:
      domain:
        cpu:
#          cores: 1
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - macAddress: 02:97:a2:00:00:c1
            masquerade: {}
            name: default
          - macAddress: 02:00:b5:b5:b5:03
            name: sriov-test-network
            sriov: {}
          rng: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 4Gi
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: sriov-test-sriov/sriov-test-network
        name: sriov-test-network
      nodeSelector:
        kubernetes.io/hostname: <cluster-node>
      terminationGracePeriodSeconds: 30
      volumes:
      - containerDisk:
          image: <base image location>:8.4-dpdk
        name: containerdisk
      - cloudInitNoCloud:
          networkData: |
            ethernets:
              '1':
                addresses:
                - 10.200.1.1/24
                match:
                  macaddress: 02:00:b5:b5:b5:03
                set-name: sriov1
            version: 2
          userData: |-
            #cloud-config
            chpasswd:
              expire: false
            password: password
            runcmd:
            - 'sudo sysctl net.ipv4.conf.all.rp_filter=2'
            - 'sudo sysctl net.ipv4.conf.all.accept_local=1'
            - 'sudo systemctl daemon-reload '
        name: cloudinitdisk
