apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-test-network
  namespace: openshift-sriov-network-operator
spec:
  ipam: '{}

    '
  networkNamespace: sriov-test-sriov
  resourceName: sriov_net
